target:
  - bad_loan

features:
  - delinq_2yrs
  - mths_since_last_delinq
  - addr_state
  - dti
  - member_id
  - loan_amnt
  - id
  - mths_since_last_record
  - funded_amnt
  - pub_rec
  - earliest_cr_line
  - inq_last_6mths
  - total_bc_limit
  - sub_grade
  - total_bal_ex_mort
  - pymnt_plan
  - desc
  - tax_liens
  - issue_d
  - term
  - home_ownership
  - total_il_high_credit_limit
  - revol_bal_joint
  - annual_inc
  - tot_hi_cred_lim
  - verification_status
  - mo_sin_rcnt_tl
  - emp_title
  - mort_acc
  - revol_bal
  - total_rec_int
  - open_acc
  - url
  - total_acc
  - revol_util
  - title
  - purpose
  - zip_code
  - initial_list_status
  - last_pymnt_d
  - emp_length
  - mths_since_recent_bc
  - total_rec_late_fee
  - mths_since_recent_bc_dlq
  - next_pymnt_d
  - last_pymnt_amnt
  - mths_since_last_major_derog
  - last_credit_pull_d
  - num_bc_sats

parameter_space:
  max_depth: [3, 4, 5, 6, 7, 10]
  num_leaves: [8, 16, 32, 64, 128]
  learning_rate: [0.01, 0.05, 0.10, 0.15]
  min_child_weight: [1, 3, 5, 7]
  gamma: [0.1, 0.2, 0.3, 0.5]
  colsample_bytree: [0.3, 0.4, 0.5, 0.7]