target:
  - bad_loan

features:
  - loan_amnt
  - int_rate
  - annual_inc
  - issue_d
  - bad_loan
  - delinq_2yrs
  - earliest_cr_line
  - inq_last_6mths
  - recoveries
  - last_pymnt_amnt
  - pub_rec_bankruptcies
  - MORTGAGE
  - OWN
  - RENT
  - car
  - credit_card
  - debt_consolidation
  - educational
  - home_improvement
  - house
  - major_purchase
  - medical
  - moving
  - other
  - renewable_energy
  - small_business
  - vacation
  - wedding
  - AK
  - AL
  - AR
  - AZ
  - CA
  - CO
  - CT
  - DC
  - DE
  - FL
  - GA
  - HI
  - IA
  - ID
  - IL
  - IN
  - KS
  - KY
  - LA
  - MA
  - MD
  - ME
  - MI
  - MN
  - MO
  - MS
  - MT
  - NC
  - NE
  - NH
  - NJ
  - NM
  - NV
  - NY
  - OH
  - OK
  - OR
  - PA
  - RI
  - SC
  - SD
  - TN
  - TX
  - UT
  - VA
  - VT
  - WA
  - WI
  - WV
  - WY
  - 36 months
  - 60 months
  - A
  - B
  - C
  - D
  - E
  - F
  - G
  - A1
  - A2
  - A3
  - A4
  - A5
  - B1
  - B2
  - B3
  - B4
  - B5
  - C1
  - C2
  - C3
  - C4
  - C5
  - D1
  - D2
  - D3
  - D4
  - D5
  - E1
  - E2
  - E3
  - E4
  - E5
  - F1
  - F2
  - F3
  - F4
  - F5
  - G1
  - G2
  - G3
  - G4
  - G5
  - 1 year
  - 10+ years
  - 2 years
  - 3 years
  - 4 years
  - 5 years
  - 6 years
  - 7 years
  - 8 years
  - 9 years
  - < 1 year
  - credit_length

parameter_space:
  max_depth: [3, 4, 5, 6, 7, 10]
  num_leaves: [8, 16, 32, 64, 128]
  learning_rate: [0.01, 0.05, 0.10, 0.15]
  min_child_weight: [1, 3, 5, 7]
  gamma: [0.1, 0.2, 0.3, 0.5]
  colsample_bytree: [0.3, 0.4, 0.5, 0.7]
